class runner{
	constructor(x,y,v){
		this.x=x;
		this.y=y;
		this.velocity=v;
		this.oxygen=1000;
		this.alive=true;
	}
	collide(){
		this.alive=false;
	}
	move(frame){
		if(keyIsPressed&&this.alive){
			if(keyIsDown(UP_ARROW)){
				this.y-=this.velocity;
				if(frame%2==0){
					this.oxygen--;
				}
			}if(keyIsDown(DOWN_ARROW)){
				this.y+=this.velocity;
				if(frame%2==0){
					this.oxygen--;
				}
			}if(keyIsDown(LEFT_ARROW)){
				this.x-=this.velocity;
				if(frame%2==0){
					this.oxygen--;
				}
			}if(keyIsDown(RIGHT_ARROW)){
				this.x+=this.velocity;
				if(frame%2==0){
					this.oxygen--;
				}
			}
		}
		if(this.x>=594){
			this.x=this.x-2;
		}if(this.x<=300){
			this.x=this.x+2;
		}if(this.y>=382){
			this.y=this.y-2;
		}if(this.y<=18){
			this.y=this.y+2;
		}
		fill(Blue);
		rect(this.x,this.y,15,15);
	}
}